language: python
sudo: required
dist: trusty
python:
    - "3.5"
before_install:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update -qq
    - sudo apt-get install -y google-chrome-stable
    - chromium-browser -version
    - sudo apt-get install unzip
    - wget -N http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip -P ~/Downloads
    - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
    - chmod +x ~/Downloads/chromedriver
    - sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
    - cd /usr/bin/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
install:
    - pip install -r requirements.txt
script:
    - python manage.py makemigrations
    - python manage.py test functional_tests
notifications:
  slack:
    on_failure: never
